# Generated by Django 4.1.4 on 2022-12-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiamodel',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='media/posts'),
        ),
    ]
