# Generated by Django 4.1.2 on 2022-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_alter_noticiamodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiamodel',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='media/noticias'),
        ),
    ]
